import type { Metadata } from "next";
import Link from "next/link";
import { OfficialLayout, PageHero } from "../official-site";
import "../editorial.css";

export const metadata: Metadata = { title: "Partnership & Ecosystem | RobiChip", description: "System, MCU, packaging, materials and developer partnerships, with custom RobiSoC co-development and a defined route from pilot to Design-in." };
const tracks = [
  ["System & Application", "系統與應用夥伴", "Robotics, UAVs, AMR / AGV, gimbals, actuators and industrial automation. Start with a motor-drive baseline, then extend to system validation.", "服務機器人、無人機、AMR／AGV、雲台、致動器與工業自動化；先建立馬達驅動評估基準，再擴展到系統驗證。", "/applications", "Explore applications · 查看應用"],
  ["MCU & Control", "MCU 與控制層夥伴", "MCU vendors, firmware teams and controller suppliers can co-develop control boards, interfaces and application-specific reference designs.", "MCU 廠商、韌體團隊與控制器供應商，共同開發控制板、介面與應用專屬參考設計。", "#control", "M1 / M2 collaboration · 控制層合作"],
  ["Packaging, Materials & Thermal", "封裝、材料與熱工程夥伴", "OSAT, substrate, materials, cooling and reliability teams align package-to-system requirements, DFM and pilot readiness.", "封裝、基板、材料、冷卻與可靠度團隊，協同定義封裝至系統需求、DFM 與試產準備。", "#packaging", "Explore integration scope · 查看整合範圍"],
  ["Education & Developer Ecosystem", "教育與開發者生態", "Universities, laboratories, research teams and developer communities use RobiDev for evaluation, teaching, firmware development and validation projects.", "大學、實驗室、研究團隊及開發者社群，透過 RobiDev 進行評估、教學、韌體開發與驗證計畫。", "/robidev", "RobiDev Ecosystem · 開發生態"],
];
export default function PartnershipPage() {
  return <OfficialLayout>
    <PageHero eyebrow="PARTNERSHIP & ECOSYSTEM · 合作與生態系" title="Build the motion platform together." titleZh="共同打造智慧動力平台。" copy="Connect complementary engineering capabilities with a concrete pilot, measured evidence and a path to Design-in." copyZh="串接互補工程能力，以具體 pilot、量測證據與設計導入路徑推進合作。" aside={<>Ecosystem: where your capability fits.<br />Partnership: how we work together.<br /><br />生態系說明能力如何互補；合作模式界定如何共同執行。</>} />
    <section className="os-content os-editorial-anchor" id="ecosystem"><div className="os-shell"><p className="os-eyebrow">FOUR ECOSYSTEM TRACKS · 四種生態合作路徑</p><h2>Find your role in the platform.<span>找到您的能力切入點。</span></h2><nav className="os-editorial-nav" aria-label="Partnership sections"><a href="#ecosystem">Ecosystem · 生態路徑</a><a href="#custom">Custom RobiSoC · 客製合作</a><a href="#evidence">Public collaboration · 公開實證</a><a href="#workflow">Working together · 合作流程</a></nav><div className="os-editorial-grid">{tracks.map(([title, zh, copy, copyZh, href, label], i) => <article className="os-editorial-card" key={title}><p className="os-eyebrow">0{i + 1}</p><h3>{title}<span>{zh}</span></h3><p>{copy}<span>{copyZh}</span></p><Link href={href}>{label} ↗</Link></article>)}</div><p className="os-note">RobiDev Discrete provides an early engineering baseline; RobiDev High-Density supports RobiSoC evaluation. A RobiThrust + RobiDev bundle extends the work to propulsion validation.<span>RobiDev Discrete 建立前期工程基準；RobiDev High-Density 支援 RobiSoC 評估；RobiThrust＋RobiDev 組合則延伸至推進系統驗證。具體配置與供應依專案確認。</span></p></div></section>
    <section className="os-content os-editorial-tint os-editorial-anchor" id="custom"><div className="os-shell"><p className="os-eyebrow">STRATEGIC CUSTOMER PROGRAM · 策略客戶合作</p><h2>Your control know-how. A customer-specific platform.<span>將控制技術，轉化為客戶專屬平台。</span></h2><p className="os-content-lead">For customer-owned algorithms, firmware, protocols, sensing and protection logic, define a Custom RobiSoC or RobiSoC-based module through confidential feasibility review and co-development.<span>涉及客戶自有演算法、韌體、通訊協定、感測與保護邏輯時，以保密可行性審查與共同開發，界定客製 RobiSoC 或模組。</span></p><div className="os-editorial-grid">{[
      ["Customer IP integration", "客戶 IP 整合", "Define the control intelligence and application behavior to integrate.", "界定需整合的控制技術、介面與應用行為。"],
      ["Custom architecture", "客製架構", "Align MCU, power stage, voltage / current range, sensing, I/O, package and thermal path.", "對齊 MCU、功率級、電壓電流範圍、感測、I/O、封裝與熱路徑。"],
      ["Confidential validation", "保密驗證", "Use RobiDev, RobiLab and application fixtures to review engineering samples against agreed requirements.", "透過 RobiDev、RobiLab 與應用治具，依約定需求檢視工程樣品。"],
      ["NRE to production supply", "從開發到產品供應", "Progress through NRE development, engineering samples, pilot builds and qualification before production planning.", "依序完成 NRE 開發、工程樣品、pilot 與資格驗證，再規劃產品供應。"],
    ].map(([t,z,c,cz]) => <article className="os-editorial-card" key={t}><h3>{t}<span>{z}</span></h3><p>{c}<span>{cz}</span></p></article>)}</div><p className="os-note">Customer background IP, RobiChip platform IP and joint improvements are identified separately. Ownership, licensing, field of use and publication terms are defined in the project agreement.<span>客戶既有 IP、羅比芯平台 IP 與共同改良成果分別界定；所有權、授權、應用領域及公開條件依專案協議約定。</span></p><Link className="os-button os-button-dark" href="/contact?intent=partnership">Request a feasibility discussion · 洽詢可行性評估 ↗</Link></div></section>
    <section className="os-content os-editorial-anchor" id="evidence"><div className="os-shell"><p className="os-eyebrow">PUBLIC COLLABORATION · 公開合作案例</p><h2>Swancor × RobiChip<span>上緯投控 × 羅比芯</span></h2><p className="os-content-lead">Advanced materials, thermal solutions and RobiChip’s Power SoC / Hybrid Substrate platform meet in a shared system-validation direction for intelligent machines.<span>結合先進材料、散熱解決方案與羅比芯 Power SoC／Hybrid Substrate 平台，共同推進智慧機器的系統驗證方向。</span></p><iframe className="os-editorial-video" src="https://www.youtube-nocookie.com/embed/RFt6A4kOUUs" title="Swancor × RobiChip strategic collaboration — May 14, 2026" loading="lazy" allow="fullscreen; picture-in-picture" allowFullScreen /><div className="os-actions"><Link className="os-button os-button-dark" href="/news-events/news-events-swancor-MOU">MOU story &amp; photos · 合作紀錄與照片 ↗</Link><Link className="os-button os-button-dark" href="/2026-TAIROS">Swancor / maxon exhibits · 展場實證 ↗</Link></div><p className="os-note">This case documents public collaboration. It does not by itself establish exclusivity, final qualification or a volume-production commitment.<span>此案例記錄已公開合作；本身不代表排他條件、最終認證或量產承諾。</span></p></div></section>
    <section className="os-content os-editorial-tint os-editorial-anchor" id="control"><div className="os-shell"><p className="os-eyebrow">M1 / M2 · CONTROL-LAYER COLLABORATION</p><h2>Keep your control differentiation.<span>保留控制層的差異化。</span></h2><p className="os-content-lead">M1 uses an STM32G4x-series baseline for initial validation. M2 is a project-based control-layer option covering customer controllers, firmware, toolchains and application-specific I/O—including CANBus, RS-485, UART, SPI, PWM, encoder feedback and current sensing.<span>M1 採用 STM32G4x-series 基準進行前期驗證；M2 則依專案整合客戶控制器、韌體、工具鏈與應用介面，例如 CANBus、RS-485、UART、SPI、PWM、編碼器回授與電流感測。</span></p><div className="os-editorial-grid"><article className="os-editorial-card"><h3>RobiChip scope<span>羅比芯分工</span></h3><p>Power architecture, GaN module direction, hybrid substrate, thermal paths, RobiSoC roadmap and RobiDev / RobiLab validation.<span>功率架構、GaN 模組方向、混合基板、熱路徑、RobiSoC 路線與評估驗證。</span></p></article><article className="os-editorial-card"><h3>Partner scope<span>夥伴分工</span></h3><p>MCU, motor-control firmware, toolchains, communications, developer support and co-developed reference designs.<span>MCU、馬達控制韌體、工具鏈、通訊、開發者支援與共同參考設計。</span></p></article></div><p className="os-note">Start with one tangible pilot: a control-board feasibility review, education kit, actuator reference design or UAV / gimbal demonstration.<span>以一項具體 pilot 起步：控制板可行性評估、教育套件、致動器參考設計，或 UAV／雲台展示。</span></p></div></section>
    <section className="os-content os-editorial-anchor" id="packaging"><div className="os-shell"><p className="os-eyebrow">PACKAGING & THERMAL · 封裝與熱工程</p><h2>From prototype to manufacturing readiness.<span>從原型驗證走向可製造性。</span></h2><div className="os-editorial-grid">{[
      ["DFM", "設計可製造性", "Substrate process rules, thermal interfaces, die attach, interconnect and layout.", "基板製程規則、熱介面、晶粒接合、互連與佈局。"],
      ["Reliability", "可靠度驗證", "Thermal / power cycling, mechanical stress, vibration, failure analysis and package-to-system validation.", "熱循環、功率循環、機械應力、振動、失效分析與封裝至系統驗證。"],
      ["Pilot production", "試產與樣品", "Sample lots, process windows, yield learning and qualification planning.", "樣品批次、製程窗口、良率學習與資格驗證規劃。"],
      ["Future scale-up", "未來量產準備", "Cost, capacity and repeatable high-power-density packaging processes.", "成本、產能與可重複的高功率密度封裝流程。"],
    ].map(([t,z,c,cz]) => <article className="os-editorial-card" key={t}><h3>{t}<span>{z}</span></h3><p>{c}<span>{cz}</span></p></article>)}</div></div></section>
    <section className="os-content os-editorial-tint os-editorial-anchor" id="workflow"><div className="os-shell"><p className="os-eyebrow">PARTNERSHIP WORKFLOW · 合作流程</p><h2>Define the first pilot together.<span>共同定義第一個合作 pilot。</span></h2><p className="os-content-lead">Roadmap exchange → technical alignment → pilot definition → joint validation → go-to-market. Each stage names the scope, owner, validation method, schedule and next decision.<span>路線交流 → 技術對齊 → pilot 定義 → 共同驗證 → 市場合作。每階段明訂範圍、負責人、驗證方式、時程與下一個決策。</span></p><p className="os-note">Public platform materials support the first discussion. Detailed datasheets, raw measurements, design files, samples and partner-specific DFM or joint-improvement work may require NDA and formal collaboration documents.<span>公開平台資料支援初步討論；詳細規格、原始量測、設計檔案、樣品及夥伴專屬 DFM／共同改良工作，依 NDA 與正式合作文件提供。</span></p><div className="os-actions"><Link className="os-button os-button-dark" href="/contact?intent=partnership">Discuss a partnership · 洽談合作 ↗</Link><a className="os-button os-button-dark" href="https://dev.robichip.com">RobiAgent Workspace · 導入工作區 ↗</a></div></div></section>
  </OfficialLayout>;
}
