import type { Metadata } from "next";
import Link from "next/link";
import { OfficialLayout, PageHero } from "../official-site";
import "../editorial.css";
export const metadata: Metadata = { title: "News & Events | RobiChip", description: "RobiChip events, post-show evidence and public milestones." };
const news = [
  ["2026-09-04", "Post-show · 展後報告", "SEMICON Taiwan 2026", "Silicon Startups Stage 與 Venture Day", "Public presentations and semiconductor-defined motion evidence, collected in the post-show virtual booth.", "整合公開演講、Venture Day 與半導體定義動力實證，於展後虛擬展間呈現。", "/semicon-taiwan-2026"],
  ["2026-08-19", "Exhibition · 展會", "TAIROS 2026", "台灣機器人與智慧自動化展", "RobiChip showcased its intelligent-motion platform through Swancor and maxon partner booths, connecting materials, motor drives and UAV validation.", "透過上緯與 maxon 夥伴展位，展示智慧動力平台，串接材料、馬達驅動與無人機驗證。", "/2026-TAIROS"],
  ["2026-07-31", "Accepted Speaker · 講者入選", "Selected for SEMICON Taiwan 2026", "羅比芯獲選 Silicon Startups Stage 講者", "Selected to present “Semiconductor-Defined Motion: High-Power-Density Motor Drive Modules for Robotics and UAVs.” The event has concluded; view the post-show report.", "獲選分享半導體定義動力平台、高功率密度馬達驅動與機器人／無人機應用。活動已結束，詳見展後報告。", "/semicon-taiwan-2026"],
  ["2026-07-02", "Forum · 論壇", "Leading 2026", "臺中無人載具產業與海外商機論壇", "Henry Gong shared perspectives on Physical AI, UAV propulsion and high-power-density motion platforms with industry and international partners.", "Henry Gong 與產業及國際夥伴分享 Physical AI、無人機推進與高功率密度智慧動力平台觀點。", "/news-events/news-events-TaiChung-UAV"],
  ["2026-06-02", "Showcase · 展示", "COMPUTEX InnoVEX 2026", "InnoVEX 新創展示牆", "RobiChip was featured on the InnoVEX Product Wall, presenting RobiSoC, RobiThrust and its intelligent-power platform roadmap.", "羅比芯入選 InnoVEX 展示牆，呈現 RobiSoC、RobiThrust 與智慧動力平台發展方向。", "/news-events/news-events-computex-InnoVEX"],
  ["2026-05-14", "Partnership · 策略合作", "Swancor × RobiChip", "策略技術合作備忘錄簽署", "A strategic technology MOU covering advanced packaging materials, thermal engineering, robotics and high-power-density motion systems.", "啟動策略技術合作，聚焦先進封裝材料、熱管理、機器人與高功率密度動力系統。", "/news-events/news-events-swancor-MOU"],
  ["2026-04-25", "Award · 獎項", "2026 Best AI Awards", "IC 設計類新創及中小企業組佳作", "Recognition for RobiChip’s high-power-density Power SoC platform for robotics and UAV motion control. The separate application finalist was submitted by a system partner.", "羅比芯的智慧機器人與無人機動力控制 Power SoC 平台獲 IC 設計類肯定；另項 AI 應用決賽作品由系統夥伴提報。", "/news-events/news-events-best-AI-Awards"],
];
export default function NewsEventsPage() {
  return <OfficialLayout>
    <PageHero eyebrow="NEWS & EVENTS · 新聞與活動" title="Milestones worth following." titleZh="追蹤平台進展，看見產業連結。" copy="Company updates, exhibitions, technology partnerships, awards and public talks across robotics, UAVs and Power SoC." copyZh="掌握機器人、無人機與 Power SoC 領域的公司動態、展會、技術合作、獎項與公開演講。" />
    <section className="os-content"><div className="os-shell"><article className="os-news-feature"><div className="os-news-date"><span>UP NEXT · 2026</span><strong>10.21</strong><span>TAIWAN TECH</span></div><div><p className="os-eyebrow">FEATURED EVENT · 近期重點活動</p><h2>Taiwan Tech Startup Connect<span>臺科育成新創交流</span></h2><p>Meet RobiChip for product demonstrations, industry connections and investor exchange at Taiwan Tech Gallery.<span>於臺科大台科藝廊與羅比芯交流產品、產業合作與投資機會。</span></p><Link className="os-button os-button-dark" href="/taiwan-tech-startup-connect">View event · 查看活動 ↗</Link></div></article></div></section>
    <section className="os-content os-editorial-tint" id="archive"><div className="os-shell"><p className="os-eyebrow">NEWSROOM · 活動紀錄</p><h2>From public milestones to engineering progress.<span>從公開里程碑，走向工程落地。</span></h2><div className="os-news-categories">{["Company Updates · 公司動態", "Exhibitions & Demo · 展會展示", "Strategic Collaboration · 策略合作", "Awards & Programs · 獎項計畫", "Talks & Forums · 演講論壇"].map(x => <span key={x}>{x}</span>)}</div><div className="os-news-list">{news.map(([date, category, title, zh, copy, copyZh, href]) => <article className="os-news-row" key={date}><div><time dateTime={date}>{date}</time><p>{category}</p></div><div><h3>{title}<span>{zh}</span></h3><p>{copy}<span>{copyZh}</span></p><Link href={href}>Read the story · 查看完整內容 ↗</Link>{date === "2026-08-19" && <Link href="/news-events/2026-TAIROS">Original announcement · 原始參展公告 ↗</Link>}</div></article>)}</div></div></section>
    <section className="os-content"><div className="os-shell"><p className="os-eyebrow">MEDIA & PARTNERSHIP · 媒體與合作</p><h2>Continue the conversation.<span>讓公開交流成為合作的起點。</span></h2><p className="os-content-lead">For interviews, event invitations, technical collaboration and partnership discussions, contact our team.<span>媒體採訪、活動邀約、技術合作與策略夥伴洽談，歡迎聯絡我們。詳細技術規格、原始驗證資料及夥伴專屬內容，依正式討論與 NDA 範圍提供。</span></p><div className="os-actions"><Link className="os-button os-button-dark" href="/contact?intent=partnership">Media / partnership inquiry · 媒體與合作洽詢 ↗</Link><a className="os-button os-button-dark" href="mailto:bd@robichip.com">bd@robichip.com</a><a className="os-button os-button-dark" href="mailto:contact@robichip.com">contact@robichip.com</a></div></div></section>
  </OfficialLayout>;
}
